import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/(components)/AuthProvider";
import GlobalNav from "@/(components)/GlobalNav";
import { NavigationMenuDemo } from "@/(components)/NavigationMenuDemo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <div
            className={
              "preview flex min-h-[350px] w-full justify-center p-10 items-center"
            }
          >
            <NavigationMenuDemo />
          </div>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
