import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/(components)/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { NavTwo } from "@/(components)/NavTwo";
import { authUser } from "@/(components)/utils/ServerUtils";
import { ServerSession } from "@/app/messages/page";
import { getServerSession } from "next-auth";
import { options } from "@/app/api/auth/[...nextauth]/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: ServerSession = (await getServerSession(
    options,
  )) as ServerSession;

  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          {session && <NavTwo currentUser={session?.user?.email} />}
          {children}
        </body>
        <Toaster />
      </AuthProvider>
    </html>
  );
}
